[package]
name = "moonlight"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "core/core",
  "core/repl",
  "modules/modules",
  "modules/dynlib_test",
  "storage/phf",
  "crypt/md5",
  "crypt/sha1",
  "crypt/sha256",
  "crypt/sha384",
  "crypt/sha512",
  "network/net",
  "network/proto",
]
resolver = "2"

[dependencies]
corelib = { path = "core/core" }
repl = { path = "core/repl" }
modules = { path = "modules/modules" }
net = { path = "network/net" }
proto = { path = "network/proto" }
phf = { path = "storage/phf" }
