[package]
name = "moonlight"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "core/core",
  "core/repl",
  "modules/modules",
  "modules/dynlib_test",
  "storage/phf",
  "crypt/md4",
  "crypt/md5",
  "crypt/sha2_224",
  "crypt/sha1",
  "crypt/sha2_256",
  "crypt/sha2_384",
  "crypt/sha2_512",
  "crypt/sha3_224",
  "crypt/sha3_256",
  "crypt/sha3_384",
  "crypt/sha3_512",
  "crypt/ripemd160",
  "crypt/ripemd320",
  "crypt/blake2b_256",
  "crypt/blake2b_512",
  "crypt/blake2s_256",
  "crypt/keccak_224",
  "crypt/keccak_256",
  "crypt/keccak_384",
  "crypt/keccak_512",
  "crypt/half_md5",
  "crypt/md6_256",
  "network/net",
  "network/proto",
]
resolver = "2"

[dependencies]
corelib = { path = "core/core" }
repl = { path = "core/repl" }
modules = { path = "modules/modules" }
net = { path = "network/net" }
proto = { path = "network/proto" }
phf = { path = "storage/phf" }
