[package]
name = "modules"
version = "0.1.0"
edition = "2021"

[dependencies]
corelib = { path = "../../core/core" }
phf = { path = "../../storage/phf" }
libc = "0.2"
md4 = { path = "../../crypt/md4" }
md5 = { path = "../../crypt/md5" }
sha224 = { path = "../../crypt/sha2_224" }
sha1 = { path = "../../crypt/sha1" }
sha256 = { path = "../../crypt/sha2_256" }
sha384 = { path = "../../crypt/sha2_384" }
sha512 = { path = "../../crypt/sha2_512" }
sha3_224 = { path = "../../crypt/sha3_224" }
sha3_256 = { path = "../../crypt/sha3_256" }
sha3_384 = { path = "../../crypt/sha3_384" }
