[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[dependencies]
corelib = { path = "../../core/core" }
net = { path = "../net" }
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "time", "macros"] }
rustls = "0.22"
tokio-rustls = "0.25"
webpki-roots = "0.26"
rustls-pemfile = "2"
h2 = "0.4.13"
http = "1"
bytes = "1"
quiche = "0.24.8"
ring = "0.17"
aes = "0.8"
ctr = "0.9"
sha1 = { path = "../../crypt/sha1" }
sha256 = { path = "../../crypt/sha256" }
sha384 = { path = "../../crypt/sha384" }
md5 = { path = "../../crypt/md5" }

[dev-dependencies]
rcgen = "0.13"
